### ISSUE TITLE
Exception UIElementExtensions.GetVisual

### ISSUE THREAD

**Issue by MuffPotter** [XamlBrewer/UWP-Composition-Radial-Gauge#1]
Just downloaded the solution.

There is an exception throw in OnApplyTemplate() (XamlBrewer.Uwp.RadialGaugeControl.RadialGauge) calling 
public static ContainerVisual GetVisual(this UIElement element)

var hostVisual = ElementCompositionPreview.GetElementVisual(element);

An exception of type 'System.InvalidCastException' occurred in XamlBrewer.Uwp.RadialGaugeControl.dll but was not handled in user code

Additional information: Unable to cast object of type 'System.__ComObject' to type 'Windows.UI.Xaml.Hosting.IElementCompositionPreviewStatics'.

**Comment by XamlBrewer** [comment]
The solution uses the release version of the Composition API, which on your side requires Visual Studio 2015 update 1, and the Windows 10 **10586** SDK (or higher). Can you please verify that you meet these requirements? The error message that you receive indicates that your machine is still running the Composition API Preview, from Windows 10 **102xx** SDK..
